### ISSUE TITLE
ASE databases scalar properties

### ISSUE THREAD

**Issue by tisabe** [peterbjorgensen/msgnet#2]
Is there a reason that in get_matproj.py the scalar properties like delta_e and band_gap are saved as key_value_pairs and in get_qm9.py the 17 properties including tag and index are saved in the "data" dictionary, while they could also be stored as key_value_pairs, if I understand the ase.db documentation correctly? This seems to make the input pipeline a bit more complicated.

**Comment by peterbjorgensen** [comment]
Yes, there is no good reason for that. It would be better to save them in the key_value_pairs to make them searchable. Some of the names should not be saved as key-value-pairs such as U0 and H, because ASE will complain that it is the same as a chemical formula.
